- Developer Version of Blackboard Applications/Using the Blackboard Learn AMI for REST and LTI Development.md
Added Let's Encrypt certificate 90 day expiry notice.
> Update Using the Blackboard Learn AMI for REST and LTI Development.md

- _data/learn.yml
- learn/Integrate with Blackboard Learn.md
- learn/LearnReleaseNamesRosettaStone.md
> Added the build number to build name mapping doc in a general category under Learn

- learn/LearnReleaseNamesRosettaStone.md
going to merge to fix the spelling. cheers
> fixed spelling

- _data/collab.yml
- _data/connecttxt.yml
- _data/openlms.yml
fixed links to connecttxt, collaborate and openlms on sitemap
> fixed links on sitemap

- BECOME AN OFFICIAL BLACKBOARD PARTNER!.md
- learn/B2s/Preparing Your Building Blocks For Learn SaaS and Newer Learn Versions.md
Just merging - please take a look at the TinyMCE 5 on PrepB2 for SaaS page. Took it almost verbatim from what Wade wrote.
> Add TinyMCE 5 doc to Prep B2 for SaaS and Change BbDN Price to What It Is Now

- standards/LTI Advantage - Names and Roles.md
> updated title

- _posts/2020-08-24-DevCon-2020-new-lti-advantage-tutorial.md
- standards/Developing an LTI Advantage Solution.md
just going to merge this. everything looked good locally.
> added latest LTI advantage tutorial from DevCon 2020

- _posts/2020-08-24-NewRESTandUEF-tutorials.md
> _posts/2020-08-24-NewRESTandUEF-tutorials.md

- learn/B2s/Preparing Your Building Blocks For Learn SaaS and Newer Learn Versions.md
except for the link to the new stuff at the top...
> pulled prior changes out

- learn/B2s/Preparing Your Building Blocks For Learn SaaS and Newer Learn Versions.md
crosses fingers after "Had to delete and regenerate the Gemfile.lock file, and also update a dependency. Should be back up and running."
> b2 mashup changes requried to address samesite

- learn/B2s/Preparing Your Building Blocks For Learn SaaS and Newer Learn Versions.md
instructions for B2s Bb Learn session cookies and SameSite mitigation
> instructions for B2s Bb Learn session cookies and SameSite mitigation

- learn/B2s/Preparing Your Building Blocks For Learn SaaS and Newer Learn Versions.md
@mark-b-kauffman
tweak the WIP section of the B2s and SameSite section
e692ad4
@mark-b-kauffman
teaking comment about coming soon to indicate what is coming soon
> adding info about what is coming soon - just pseudo code or a sample

- learn/B2s/First Project - Gradle, Git, and b2-starter-template.md
no spaces in vendor id or handle  - don't do it!
> no spaces in vendor id or handle

- _posts/2021-05-10-use one time session tokens instead of cookies for UEF authentication.md
Deleted a no breaking space to fix a line break and a space before the 3LO link so it's clickable.
> Deleted a nbsp; and a space that was messing with the format of the post

- collaborate/security-and-tokens.md
Also fixed some formatting and broken links
> updated the description of the Build a JWT section

- _layouts/home.html
> updated home link

- rest-apis/ally/about-api-documentation.md
- rest-apis/ally/get-feedback.md
- rest-apis/ally/getting-started.md
- rest-apis/collaborate/creating-sessions-with-rest.md
- rest-apis/collaborate/first-steps.md
- rest-apis/collaborate/getting-started.md
- rest-apis/collaborate/sandbox.md
> Fixed broken links

- rest-apis/ally/about-api-documentation.md
> removing toc 

- _includes/footer.html
- _includes/header.html
> Fixed bugs with the menu

- _includes/footer.html
- assets/css/main.css
updates and bug fixes to the menu
> More updates

- rest-apis/learn/getting-started/adaptive-release.md
> Adaptive release

- lti/tutorials/py-lti-1p3.md
This isn't complete because I ran into a problem running the app due to a conflict with the version of Flask. I don't know when I'll get around to this again, but it seems better than not making the changes at all. Perhaps one of you could run through it?
> updated instructions for getting the pylti13 sample working in Learn
